security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            logout:
                path: app_logout
            form_login:
                login_path: /login
                check_path: /login
                enable_csrf: false
            http_basic: ~

    access_control:
        - { path: ^/api/reports, roles: ROLE_USER }
        - { path: ^/api/expenses, roles: ROLE_USER }
        - { path: ^/api/categories, roles: ROLE_USER }
        - { path: ^/api/users, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    enable_authenticator_manager: true
